# site settings
title: Clara 
subtitle: Ponce Grosso
email: claraponce.psicologia@gmail.com
description: Tu Psicóloga en Málaga y Online
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: C/ Eslava 14 2º, 29002 (Málaga)
city: Málaga
state: Málaga
zip_code: 29002
country: España
phone: 623 137 090

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Instagram: https://www.instagram.com/claraponce.psicologia/
  LinkedIn: https://www.linkedin.com/in/clara-ponce-grosso-2a1027150/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
